### ISSUE TITLE
Crash after giving health permissions - EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by elleven11** [loopnlearn/LoopWorkspace#29]
The Loop builds fine.
However, right after installing the app and giving health permission the application crashes, and in xcode it gets reported as a EXC_BAD_ACCESS code 1 in LoopKit/LoopKit/HealthKitSampleStore line 174

I am on IOS 14.7.1, macOS 12.2.1 and Xcode13.3

I have tried to update the LoopKit submodule to the latest version, but didn't work.
However, the normal Loop branch builds and runs fine.

**Comment by marionbarker** [comment]
Are you building from LoopWorkspace. 
Are you using the Build Select script?
If not, please read the README.md file and follow those directions and links.

**Comment by elleven11** [comment]
Yes. I have also tried both on an M1 and Intel macbook. Same issue.
I have been looping for a while, never encountered this issue. Going through the debugger it seems like the newValue variable is being assigned to nil for some reason

**Comment by marionbarker** [comment]
This was fixed today.  Please see these release notes:
https://github.com/loopnlearn/LoopWorkspace/releases/tag/v2.2.204.xcode13.3_hotfix
